// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC97evngP0CUg0S-BiwpvliwqPc-3bb8XE',
    appId: '1:216142571388:web:c4db03b943414582f0a6f9',
    messagingSenderId: '216142571388',
    projectId: 'tp-flutter-60de6',
    authDomain: 'tp-flutter-60de6.firebaseapp.com',
    storageBucket: 'tp-flutter-60de6.firebasestorage.app',
    measurementId: 'G-TS87W0Z69W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbAro6R35uXtbCKE42hqHAElrTrhJBnVg',
    appId: '1:216142571388:android:a3afd2c6b42696b4f0a6f9',
    messagingSenderId: '216142571388',
    projectId: 'tp-flutter-60de6',
    storageBucket: 'tp-flutter-60de6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgvVgyrgsWPU7xsPvJ0jMt_XkAMtXbuUM',
    appId: '1:216142571388:ios:6597393aeb1032fbf0a6f9',
    messagingSenderId: '216142571388',
    projectId: 'tp-flutter-60de6',
    storageBucket: 'tp-flutter-60de6.firebasestorage.app',
    iosBundleId: 'com.example.clstapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBgvVgyrgsWPU7xsPvJ0jMt_XkAMtXbuUM',
    appId: '1:216142571388:ios:6597393aeb1032fbf0a6f9',
    messagingSenderId: '216142571388',
    projectId: 'tp-flutter-60de6',
    storageBucket: 'tp-flutter-60de6.firebasestorage.app',
    iosBundleId: 'com.example.clstapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC97evngP0CUg0S-BiwpvliwqPc-3bb8XE',
    appId: '1:216142571388:web:ccbb87c50f10361bf0a6f9',
    messagingSenderId: '216142571388',
    projectId: 'tp-flutter-60de6',
    authDomain: 'tp-flutter-60de6.firebaseapp.com',
    storageBucket: 'tp-flutter-60de6.firebasestorage.app',
    measurementId: 'G-P46FPNP3KQ',
  );

}